# Generated by Django 4.2.6 on 2024-03-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='user_id',
        ),
    ]
