# Generated by Django 4.2.6 on 2024-03-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_document_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
